# Generated by Django 5.2.4 on 2025-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='개발툴 이름')),
                ('kind', models.CharField(max_length=100, verbose_name='종류')),
                ('content', models.TextField(verbose_name='설명')),
            ],
        ),
    ]
